# Generated by Django 4.1.1 on 2022-09-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150, verbose_name='Название банка')),
                ('term_min', models.IntegerField(default='10', verbose_name='Срок ипотеки, ОТ')),
                ('term_max', models.IntegerField(default='30', verbose_name='Срок ипотеки, ДО')),
                ('rate_min', models.FloatField(default=1.8, verbose_name='Ставка, ОТ')),
                ('rate_max', models.FloatField(default=9.8, verbose_name='Ставка, ДО')),
                ('payment_min', models.IntegerField(default='1000000', verbose_name='Сумма кредита, ОТ')),
                ('payment_max', models.IntegerField(default='10000000', verbose_name='Сумма кредита, ДО')),
            ],
            options={
                'verbose_name': 'Ипотечное предложение',
                'verbose_name_plural': 'Ипотечные предложения',
            },
        ),
    ]
